collections:
  - name: "pages"
    label: "Seiten"
    files:
      - file: "../index.html"                  # geht eine Ebene hoch zu docs/
        label: "Startseite"
        name: "home"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Text", name: "body", widget: "markdown" }
      - file: "../impressum/impressum.html"
        label: "Impressum"
        name: "impressum"
        fields:
          - { label: "Text", name: "body", widget: "markdown" }
      - file: "../datenschutz/datenschutz.html"
        label: "Datenschutz"
        name: "datenschutz"
        fields:
          - { label: "Text", name: "body", widget: "markdown" }