backend:
  name: github
  repo: DEIN_GITHUB_USERNAME/Website-1
  branch: main

media_folder: "docs/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Seiten"
    files:
      - file: "docs/index.html"
        label: "Startseite"
        name: "home"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Text", name: "body", widget: "markdown" }
      - file: "docs/datenschutz/datenschutz.html"
        label: "Datenschutz"
        name: "datenschutz"
        fields:
          - { label: "Text", name: "body", widget: "markdown" }
      - file: "docs/impressum/impressum.html"
        label: "Impressum"
        name: "impressum"
        fields:
          - { label: "Text", name: "body", widget: "markdown" }